std_flame_flare:
  apps:
    tk-flame-export:
      batch_publish_type: Flame Batch File
      batch_template: flame_shot_batch
      bypass_shotgun_transcoding: false
      location: {name: tk-flame-export, type: app_store, version: v1.3.5}
      menu_name: Shotgun Shot Export
      plate_presets:
      - {name: 10 bit DPX, publish_type: Flame Render, quicktime_publish_type: Flame
          Quicktime, quicktime_template: null, template: flame_shot_render_dpx, upload_quicktime: true}
      - {name: 16 bit OpenEXR, publish_type: Flame Render, quicktime_publish_type: Flame
          Quicktime, quicktime_template: null, template: flame_shot_render_exr, upload_quicktime: true}
      segment_clip_template: flame_segment_clip
      settings_hook: '{self}/settings.py'
      shot_clip_template: flame_shot_clip
      shot_parent_entity_type: Sequence
      shot_parent_link_field: sg_sequence
      shot_parent_task_template: ''
      task_template: Basic shot template
    tk-flame-review:
      location: {name: tk-flame-review, type: app_store, version: v1.0.5}
      menu_name: Submit for Shotgun review
      settings_hook: '{self}/settings.py'
      shotgun_entity_type: Sequence
      task_template: ''
  backburner_shared_tmp: /tmp
  debug_logging: false
  flame_batch_publish_type: Flame Batch File
  location: {name: tk-flame, type: app_store, version: v1.3.4}
  project_startup_hook: '{self}/project_startup.py'
