nk_image_formats: 
     - file_type: exr
          name: 'Stereo Exr, 16 bit'
          proxy_publish_template: null
          proxy_render_template: null
          publish_template: nuke_shot_render_pub_stereo
          render_template: nuke_shot_render_stereo
          settings: {datatype: 16 bit half}
          tank_type: Rendered Image
          tile_color: []
          
     # - file_type: dpx
     #      name: Mono Dpx
     #      proxy_publish_template: null
     #      proxy_render_template: null
     #      publish_template: nuke_shot_render_pub_mono_dpx
     #      render_template: nuke_shot_render_mono_dpx
     #      settings: {}
     #      tank_type: Rendered Image
     #      tile_color: []
     # - file_type: jpg
     #      name: Jpeg
     #      proxy_publish_template: null
     #      proxy_render_template: null
     #      publish_template: nuke_shot_render_pub_jpg
     #      render_template: nuke_shot_render_jpg
     #      settings: {}
     #      tank_type: Rendered Image
     #      tile_color: []

