# Shotgun Pipeline Toolkit configuration file
# this file was automatically created

host: https://thearteryvfx.shotgunstudio.com
api_script: Toolkit
api_key: eec55f46b00d478f6e86f1c419008d78db54940e94e935cd5e6f5f4d2125f27f
http_proxy: null

# End of file.
